services:
  postgres:
    image: postgres:16
    container_name: postgres_credit_api
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credit_api"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: fastapi_credit_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/credit_api
      MODEL_PATH: /app/artifacts/model.joblib
      MODEL_VERSION: v1
      SIMULATION_SOURCE_CSV: /app/data/application_test.csv
      DATA_PATH: /app/data
      MONITORING_DIR: /app/artifacts/monitoring
      PYTHONPATH: /app
    command:
      [
        "uv", "run", "uvicorn",
        "app.main:app",
        "--host", "0.0.0.0",
        "--port", "8000"
      ]
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
      - ./app:/app/app

  dashboard:
    build: .
    container_name: streamlit_credit_dashboard
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/credit_api
      API_URL: http://api:8000
      DEFAULT_LIMIT: 200
      DATA_PATH: /app/data
      PYTHONPATH: /app
    command:
      [
        "uv", "run", "streamlit", "run",
        "dashboard/dashboard_main.py",
        "--server.address=0.0.0.0",
        "--server.port=8501"
      ]
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app/dashboard
      - ./artifacts:/app/artifacts
      - ./app:/app/app
      - ./data:/app/data

volumes:
  postgres_data: